server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #指定 namespace
        namespace: 4c6a61af-7019-4bda-a83b-e4ebb8edcdd4
        #指定集群
        cluster-name: NJ
    gateway:
      discovery:
        locator:
          #让gateway通过服务发现组件找到其他的微服务
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
