#所有环境公用属性
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    health:
#      show-details: always
#连字符
spring:
  profiles:
    active: dev
---
#profile=x的专用属性，也就是某个环境下的专用属性
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
  ##服务名称
  application:
    name: rosefinch-web
server:
  port: 8082
---
spring:
  profiles: prod
server:
  tomcat:
    max-threads: 300
    max-connections: 1000