#所有环境公用属性
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    health:
#      show-details: always
#连字符
spring:
  profiles:
    active: dev
---
#profile=x的专用属性，也就是某个环境下的专用属性
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
        #指定 namespace
        namespace: 4c6a61af-7019-4bda-a83b-e4ebb8edcdd4
        #指定集群
        cluster-name: NJ
  datasource:
    ## 配置连接池
    type: com.alibaba.druid.pool.DruidDataSource
    ## 配置数据库连接信息
    url: jdbc:mysql://192.168.2.217:3306/rosefinch?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  ##服务名称
  application:
    name: rosefinch-business
mybatis:
  #mybatis配置文件
  config-location: classpath:/mybatis-config.xml
server:
  port: 8081
---
spring:
  profiles: prod
server:
  tomcat:
    max-threads: 300
    max-connections: 1000